development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: schoolfinder_development
  pool: 5
  username: pguser
  password: irentex9092


test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: schoolfinder_test
  username: pguser
  password: irentex9092